# Generated by Django 4.1 on 2022-11-29 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0003_post_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["created_on"]},
        ),
        migrations.RenameField(
            model_name="comment", old_name="content", new_name="body",
        ),
        migrations.RemoveField(model_name="comment", name="website",),
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment", name="email", field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="comment", name="name", field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="bookMng.post",
            ),
        ),
    ]
