# Generated by Django 4.1 on 2022-11-29 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookMng", "0004_alter_comment_options_rename_content_comment_body_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(name="post", options={},),
        migrations.RenameField(model_name="post", old_name="content", new_name="body",),
        migrations.RemoveField(model_name="post", name="created_on",),
        migrations.RemoveField(model_name="post", name="slug",),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="Comment",),
    ]
