# Generated by Django 4.1 on 2022-11-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0005_alter_post_options_rename_content_post_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
    ]
