# Generated by Django 4.1 on 2022-11-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0007_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="This",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
    ]
