# Generated by Django 4.1 on 2022-11-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0008_this"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="author",),
        migrations.DeleteModel(name="This",),
        migrations.DeleteModel(name="Post",),
    ]
