# Generated by Django 4.1 on 2022-11-30 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookMng", "0010_post_comment"),
    ]

    operations = [
        migrations.RemoveField(model_name="comment", name="parent",),
        migrations.AlterField(
            model_name="comment",
            name="CommentPost",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookMng.book"
            ),
        ),
        migrations.DeleteModel(name="Post",),
    ]
